config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "/dashboard", to: "pages#dashboard"
  get "/my-bookings", to: "pages#my_bookings"
  get "/my-studios", to: "pages#my_studios"

  resources :studios do
    resources :bookings, only: :create do
      member do
        get :booking_confirmation
      end
    end
   end
    resources :bookings, only: %i[destroy edit update show]
    get 'search', to: 'studios#search'
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :studio

  validates :total_price, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
  validate :end_date_after_start_date

  private


  def end_date_after_start_date
    return if end_time.blank? || start_time.blank?

    if end_time < start_time
      errors.add(:end_time, "must be after the start time")
    end
  end
end

app/models/studio.rb
class Studio < ApplicationRecord

  # has_many :bookings, dependent: :destroy
  # has_many :users, through: :bookings
  has_one_attached :photo

  has_many :bookings, dependent: :destroy
  has_many :users, through: :bookings

  belongs_to :user

  validates :name, :description, :price_per_hour, :is_soundproof, :location, :max_occupancy, presence: true

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :bookings
  has_many :studios, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :first_name, :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.all
  end

  def create
    @studio = Studio.find(params[:studio_id])
    @booking = Booking.new(booking_params)
    @booking.studio = @studio
    @booking.user = current_user
    total_time = ((@booking.end_time - @booking.start_time) / 3600).round
    @booking.total_price = total_time * @studio.price_per_hour
    if @booking.save
      redirect_to booking_confirmation_studio_booking_path(@studio, @booking)
    else
      render "studios/show", status: :unprocessable_entity
    end
  end

  def edit
    @booking = Booking.find(params[:id])
  end

  def update
    @booking = Booking.find(params[:id])
    if @booking.update(booking_params)
      redirect_to dashboard_path
    else
      render :edit
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to studio_path(@booking.studio), status: :see_other
  end


  def booking_confirmation
    @studio = Studio.find(params[:studio_id])
    @booking = Booking.find(params[:id])
  end

  private

  def booking_params
    params.require(:booking).permit(:start_time, :end_time, :booked_at, :total_price)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end

  def dashboard
    @user = current_user
    @user.studios.each do |studio|
      Booking.where(studio_id: studio.id) if Booking.where(studio_id: studio.id).exists?
    end
  end

  def my_studios
    @user = current_user
  end

  def my_bookings
    @user = current_user
  end
end

app/controllers/studios_controller.rb
class StudiosController < ApplicationController
  def index
    @studios = Studio.all
    @markers = @studios.geocoded.map do |studio|
      {
        lat: studio.latitude,
        lng: studio.longitude
      }
    end
  end

  def show
    @studio = Studio.find(params[:id])
    @booking = Booking.new
    @markers = [
      {
        lat: @studio.latitude,
        lng: @studio.longitude
      }
    ]
  end

  def new
    @studio = Studio.new
  end

  def create
    @studio = Studio.new(studio_params)
    @studio.user = current_user
    if @studio.save
      redirect_to studio_path(@studio)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @studio = Studio.find(params[:id])
  end

  def update
    @studio = Studio.find(params[:id])
    if @studio.update(studio_params)
      redirect_to studios_path
    else
      render :edit
    end
  end

  def search
    @location = params[:location]
    @max_occupancy = params[:max_occupancy].to_i
    if params[:location].present?
      sql_query = "location ILIKE :location AND max_occupancy <= :max_occupancy"
      @studios = Studio.where(sql_query, location: "%#{params[:location]}%", max_occupancy: params[:max_occupancy].to_s)
    else
      @studios = Studio.all
    end
  end

  def booking_confirmation
    @studio = Studio.find(params[:id])
  end

  private

  def studio_params
    params.require(:studio).permit(:name, :description, :price_per_hour, :is_soundproof, :location, :max_occupancy, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/booking_confirmation.html.erb
<div class="main_show">
  <div class="container_show">
    <div class="confirmation">
      <h1>Booking with <%= @studio.name %> Confirmed!</h1>
      <%= cl_image_tag @studio.photo.key %>
      <p>Thank you for booking our music studio. We look forward to seeing you soon!</p>
      <div class="buttons">
        <%= link_to "Edit Booking", edit_booking_path(@booking), class: 'button1' %>
        <%= link_to "Delete Booking", booking_path(@booking), class: 'button2', data: {turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this booking?"} %>
      </div>
    </div>
  </div>
</div>

app/views/bookings/edit.html.erb
<%= simple_form_for @booking do |f|%>
  <div class="checkin">
    <label for="checkin">Check-in:</label>
    <div class="dateandtime">
      <%= f.input :start_time, as: :date, html5: true %>
      <%= f.input :start_time, as: :time, html5: true %>
    </div>
  </div>
  <div class="checkout">
    <label for="checkout">Check-out:</label>
      <div class="dateandtime">
        <%= f.input :end_time, as: :time, html5: true %>
      </div>
  </div>
  <div class="btn btn-flat-show">
    <%= f.submit %>
  </div>
<% end %>

app/views/bookings/new.html.erb
<%= simple_form_for @booking do |f| %>
  <div class="form-inputs">
    <%= f.input :checkin_date, as: :date, label: "Check-in", required: true %>
    <%= f.input :checkin_time, as: :time, label: false, required: true %>
    <%= f.input :checkout_time, as: :time, label: "Check-out", required: true %>
  </div>
  <div class="form-actions">
    <%= f.button :submit, "Book Now", class: "btn btn-flat-show" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TREESoundStudios</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="stylesheet" href="https://kit.fontawesome.com/887d8d6ddd.css" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Lato&display=swap" rel="stylesheet">
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
  </head>
  <body>
    <div class="page-container">
      <%= render "shared/navbar" %>
      <main id="main-content">
        <%= yield %>
      </main>
      <%= render "shared/footer" %>
    </div>
    <%= render "shared/flashes" %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="main-dash">
  <div class="banner_guitar" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.ctfassets.net/bdyhigkzupmv/6lySzcy7qcIN1tf81Qkus/5b5ac73daeaf61f9057c0b0dd8447a31/hero-guitar-outro.jpg);">
      <h1><strong>Hello Kurt Cobain!</strong></h1>
  </div>
    <div class="d-flex flex-row" style="min-height: 100vh">
      <div class="container-all-dash">
        <div class="container-dash">
          <div class="user-photo">
              <%= image_tag "kurt-cobain.jpg" %>
              <h2><strong>Kurt Cobain</strong></h2>
                <div class="details-user">
                  <p><i class="fa-solid fa-location-dot"></i> Sky Land</p>
                  <p><strong>Instruments: </strong>Guitar</p>
                  <p><strong>E-mail: </strong>kurt.cobain27@thesky.com</p>
                  <p><strong>Password: </strong>****************</p>
                </div>
          </div>
        </div>
        <div class="all-details">
          <div class="bookings-dash">
            <h2 class="bookings-studios">My Bookings</h2>
              <% if @user.bookings.any? %>
                <% @user.bookings.each do |booking| %>
                  <div class="card" style="width: 18rem;">
                    <%= cl_image_tag booking.studio.photo.key %>
                    <h2><%= booking.studio.name %></h2>
                    <p>From <%= booking.start_time %></p>
                    <p>To <%= booking.end_time %></p>
                    <br>
                  </div>
                <% end %>
              <% else %>
                <%= "You have no bookings scheduled!" %>
              <% end %>
          </div>
          <div class="studios-dash">
            <h2 class="bookings-studios">My Studios</h2>
              <% if @user.studios.any? %>
                <% @user.studios.each do |studio| %>
                  <div class="card" style="width: 18rem;">
                    <%= cl_image_tag studio.photo.key %>
                    <h2><%= studio.name %></h2>
                  </div>
                <% end %>
              <% else %>
                <%= "You have no studios created!" %>
              <% end %>
          </div>
        </div>
      </div>
    </div>
</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://blog.bammusic.com/wp-content/uploads/2021/08/caught-in-joy-ptVBlniJi50-unsplash-min-scaled.jpg);">
  <div class="home">
    <h1><strong>Tree Sound Studios</strong></h1>
    <p>The roots of sound!</p>

    <%= link_to "See all Studios", studios_path, class: "btn btn-flat" %>

  </div>
</div>

app/views/pages/my_bookings.html.erb
<% @user.bookings.each do |booking| %>
  <%= link_to booking_path(booking) do %>
    <div class="card">
      <h2 class="title"><%= booking.name %></h2>
     </div>
     <p><%= link_to "Edit Booking", edit_booking_path(booking) %></p>
     <p><%= link_to "Delete Booking", my_bookings_path(booking), data: {turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this booking??"} %></p>
  <% end %>
<% end %>

app/views/pages/my_studios.html.erb
<% @user.studios.each do |studio| %>
  <%= link_to studio_path(studio) do %>
    <div class="card">
      <h2 class="title"><%= studio.name %></h2>
    </div>
    <p><%= link_to "Edit Studio", edit_studio_path(studio) %></p>
    <p><%= link_to "Delete Studio", my_studios_path(studio), data: {turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this studio?"} %></p>
  <% end %>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    © Tree Sound Studios | 2023
  </div>
  <div class="footer-copyright">
    This footer was made by © Tree Roots<%= image_tag("tree.svg", width: "25px") %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon w-100" style="z-index: 1">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo.svg" %>
    <% end %>

  <div class="">
    <%= form_with url: search_path, method: :get, class: "d-flex bar" do %>
      <%= text_field_tag :location,
        params[:location],
        class: "form-control location",
        placeholder: "Where are you going ?"
      %>
      <br>
      <%= text_field_tag :max_occupancy,
        params[:max_occupancy],
        class: "form-control occupancy",
        placeholder: "Occupants"
      %>
      <br>
      <%= button_tag(type: "submit", style: "border: none;") do %>
        <i class="fa-solid fa-magnifying-glass"></i>
      <% end %>
    <% end %>
  </div>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "List studios", studios_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://www.vogue.pt/media/content/kurt-cobain-feminismo-curiosidades.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Dashboard", dashboard_path, class: "dropdown-item" %>
              <%= link_to "List a Studio", new_studio_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Log in", new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item2">
            <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/studios/index.html.erb
<%# <%= render "map" %> %
<%#
<hr> %>
<div class="banner_guitar" data-controller="audio" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.ctfassets.net/bdyhigkzupmv/6lySzcy7qcIN1tf81Qkus/5b5ac73daeaf61f9057c0b0dd8447a31/hero-guitar-outro.jpg);">
    <h1><strong>Best Studios in this area:</strong></h1>
</div>

<div class="cards m-5">
  <% @studios.each do |studio| %>
    <%= link_to studio_path(studio), class:"text-decoration-none" do %>
      <% if studio.photo.attached? %>
        <div class="card-category" style="height: 400px; background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)),
          url('<%= cl_image_path studio.photo.key, height: 300, crop: :fill %>')">
            <h1><%= studio.name %></h1>
            <h2><i class="fa-solid fa-location-dot"></i> <%= studio.location %></h2>
            <br>
            <p><%= studio.price_per_hour %>€/h</p>
        </div>
      <% else %>
        <div class="card-category" style="height: 400px; background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)),
          url('<%= image_path "tree.svg" %>')">
          <h1><%= studio.name %></h1>
          <i class="fa-solid fa-location-dot"></i> <%= studio.location %>
          <br>
          <%= studio.price_per_hour %>€/h
        </div>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/studios/new.html.erb
<div class="new_studio_form">
<h2 class="header">Your studio</h2>
<%= simple_form_for(@studio) do |f| %>
  <h3 class="text"><%= f.input :name %></h3>
  <h3 class="text"><%= f.input :description %></h3>
  <h3 class="text"><%= f.input :price_per_hour %></h3>
  <h3 class="text"><%= f.input :location %></h3>
  <h3 class="text"><%= f.input :max_occupancy %></h3>
  <h3 class="text"><%= f.input :is_soundproof %></h3>
  <h3 class="text"><%= f.input :photo, as: :file %></h3>
  <div class="button-create"><%= f.submit %></div>
<% end %>
</div>

app/views/studios/search.html.erb
<div class="banner_guitar" data-controller="audio" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.ctfassets.net/bdyhigkzupmv/6lySzcy7qcIN1tf81Qkus/5b5ac73daeaf61f9057c0b0dd8447a31/hero-guitar-outro.jpg);">
    <h1><strong>Studios in <%= @location %> for <%= @max_occupancy %> musicians:</strong></h1>
</div>

<div class="cards m-5">
  <% @studios.each do |studio| %>
    <%= link_to studio_path(studio), class:"text-decoration-none" do %>
      <% if studio.photo.attached? %>
        <div class="card-category" style="height: 400px; background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)),
          url('<%= cl_image_path studio.photo.key, height: 300, crop: :fill %>')">
            <h1><%= studio.name %></h1>
            <h2><i class="fa-solid fa-location-dot"></i> <%= studio.location %></h2>
            <br>
            <p><%= studio.price_per_hour %>€/h</p>
        </div>
      <% else %>
        <div class="card-category" style="height: 400px; background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)),
          url('<%= image_path "tree.svg" %>')">
          <h1><%= studio.name %></h1>
          <i class="fa-solid fa-location-dot"></i> <%= studio.location %>
          <br>
          <%= studio.price_per_hour %>€/h
        </div>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/studios/show.html.erb
<div class="container d-flex mt-4">
  <div class="row container_show">
    <div class="studio-image text-white d-flex justify-content-center align-items-center" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path @studio.photo.key %>)">
      <h2 class="show_name text-center"><%= @studio.name %></h2>
    </div>

    <div class="d-flex col-12">
      <div class="textandbook">
        <div class="details">
          <p><strong>Description: </strong><%= @studio.description%></p>
          <p><strong>Location: </strong><%= @studio.location %></p>
          <p><strong>Price per hour: </strong><%= number_to_currency(@studio.price_per_hour) %></p>
          <p><strong>Soundproof: </strong><%= @studio.is_soundproof ? "Yes" : "No" %></p>
          <p><strong>Max Occupancy: </strong><%= @studio.max_occupancy %></p>
        </div>
      </div>

      <div class="booking-form mt-4">
        <%= simple_form_for [@studio, @booking] do |f|%>
          <div class="checkin">
            <label for="checkin">Check-in:</label>
            <div class="dateandtime">
              <%= f.input :start_time, as: :date, html5: true %>
              <%= f.input :start_time, as: :time, html5: true %>
            </div>
          </div>
          <div class="checkout">
            <label for="checkout">Check-out:</label>
              <div class="dateandtime">
                <%= f.input :end_time, as: :time, html5: true %>
              </div>
          </div>
          <div>
            <%= f.submit class: "btn btn-flat-show" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="col-6 ms-3" style="width: 50%; height: calc(100vh - 106px); position: sticky; top: 106px;"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>